### ISSUE TITLE
Añadir precios horarios

### ISSUE THREAD

**Issue by frentemorao** [jirsis/JIR-tarifa-luz#1]
Buenas.
Recientemente he transicionado de Dakboard a MagicMirror por su modularidad y me he llevado la grata sorpresa de tus módulos en español.

Me gustaría integrar los precios horarios del pvpc en mi dashboard, pero mi capacidad de programación es nula.
He encontrado páginas que "wrappean" los datos de Red Eléctrica (tarifaluzhora.es o https://www.datawrapper.de/_/DAhIR/) por lo que entiendo no debería ser complicado integrarlos en un módulo de MM, si sabes programar claro.

Por ello te animo a completar tu módulo con los precios, pues sería de gran ayuda, entre otros para mí jeje

**Comment by jirsis** [comment]
Hola, buenos días:

Muchas gracias por los comentarios. La verdad es que lo estuve valorando en
su momento y a mi no me parecía interesante, jejeje. De todas formas estoy
investigando de donde sacar la información y  a ratitos iré completándola.
La idea que tenía con este módulo era hacerlo sencillo y que no necesitase
fuentes externas. Para pintar un semáforo en función del día y las horas
era sencillo.

De todas formas, lo que te comento. Estoy investigando de donde sacar la
información, que supongo que será algún servicio de Red Eléctrica y en
cuanto consiga algo lo subiré.

Un saludo y muchas gracias por el comentario.

**Comment by frentemorao** [comment]
Efectivamente la web de la que tomar los datos es la de Red Eléctrica (en concreto https://www.esios.ree.es/es/pvpc ó https://www.esios.ree.es/en/embed/active-energy-invoicing-price-pvpc)

Pero lo que te decía, quizá se pueda aprovechar el trabajo de otros... 
- tarifaluzhora.es
- https://www.datawrapper.de/_/DAhIR/
- https://www.home-assistant.io/integrations/pvpc_hourly_pricing/
- o incluso desde google sheets >> https://docs.google.com/spreadsheets/d/1Rx6fvX1dyOOF-ZztfFfB9nXN4gDnrxg3De1qkg70EMI/edit#gid=0

Lo único que puedo decirte es que mucho ánimo!!

**Comment by frentemorao** [comment]
Añado un último comentario... he encontrado gran parte del trabajo hecha:
- https://github.com/azogue/esiosdata
- https://github.com/azogue/aiopvpc

está en python... no sé si será sencillo de integrar para mm

**Comment by jirsis** [comment]
Ayer estuve haciendo alguna pruebeceilla y en cuanto tenga más rato, dejaré subida una primera versión a ver que tal resulta.

**Comment by frentemorao** [comment]
Perfecto, eso es rapidez, jeje!!
Por si te ayuda, a mí me gusta la visualización de tarifaluzhora.es pero ojo, no la del pc sino la del móvil:
![Screenshot_20210928-154426_Firefox](https://user-images.githubusercontent.com/3320661/135103144-281f6954-4d87-4193-8c8a-ba6aae184e0c.jpg)

**Comment by jirsis** [comment]
Por ahora va una primera versión, sencilla y rápida. Se muestra el precio de la luz en el momento. Algo sencillo de ver, sencillo de desarrollar sin tener que rehacer mucho de lo que ya está y creo que suficiente.

**Comment by frentemorao** [comment]
Buenas y de nuevo, gracias por el trabajo. 

No consigo que me muestre el precio... ni con el token personal que he solicitado ni con el tuyo:
![imagen](https://user-images.githubusercontent.com/3320661/135503011-c4538898-97e9-43d2-a5c8-31354cc5b7f8.png)

Esta es mi configuración:
```
             {
                        module: "JIR-tarifa-luz",
                        position: "top_left",
                        config: {
                                showprice: "true",
                                esiosToken: "6753856a894a0a3b27bb41cb7843db6f2d2eb88ab8cf3d49b7e39f7980cef700"
                        }
                },
```
Qué puede estar mal??

PD1 en el readme tienes puesto show**P**rice pero sólo me funciona en minúsculas (show**p**rice)
PD2 creo que hay una errata también en el readme >> aparece `true con una `

**Comment by frentemorao** [comment]
Buenas de nuevo y muchas gracias por el trabajo

Después de varias pruebas, lo he conseguido con esta configuración!!!

```
 {
                        module: "JIR-tarifa-luz",
                        position: "bottom_right",
                        config: {
                                showPrice: "true",
                                esiosToken: "6753856a894a0a3b27bb41cb7843db6f2d2eb88ab8cf3d49b7e39f7980cef700",
                                esiosLocation: 8741
                        }
                },
```

**Comment by jirsis** [comment]
Jejejeje, "mi" token es normal que no te funcione. Es uno que encontré en la documentación de esios y probablemente haya caducado. El mío como tal intento no guardarlo en claro en repositorios por posibles problemas legales. 

En cuanto a las configuraciones, es extraño. El showPrice es un booleano, por lo que funciona sin comillas dobles y el de esiosLocation tiene puesto un valor por defecto que es justo ese. 

Pero bueno, si lo has conseguido echar a andar, enhorabuena. Cualquier cosa que veas coméntalo y si lo puedo solucionar, lo haré 😄

**Comment by frentemorao** [comment]
realmente me funcionó con mi token y no con el "tuyo"

**Comment by jirsis** [comment]
Implementado en la versión v0.4.2
